
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiseka
 */
public class DataDokumen extends javax.swing.JPanel {
    DefaultTableModel model;
    String filename=null;

    
    public DataDokumen() {
        initComponents();
        
        //membuat header pada tabel
        Object[] header = {"No","Kode Dokumen","Nama Dokumen",
            "Kategori Dokumen","Lokasi Dokumen","Deskripsi Dokumen","Tanggal"};
        model = new DefaultTableModel(header, 0);
        tblDokumen.setModel(model);
        tblDokumen.setRowHeight(10);
        tblDokumen.getColumnModel().getColumn(0).setMinWidth(100);
        tblDokumen.getColumnModel().getColumn(0).setMaxWidth(100);
        tblDokumen.getColumnModel().getColumn(1).setMinWidth(0);
        tblDokumen.getColumnModel().getColumn(1).setMaxWidth(0);
        loadData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDokumen = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(52, 82, 111));

        btnTambah.setBackground(new java.awt.Color(102, 102, 102));
        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah Data");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblDokumen.setBackground(new java.awt.Color(52, 73, 94));
        tblDokumen.setForeground(new java.awt.Color(255, 255, 255));
        tblDokumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblDokumen.setPreferredSize(new java.awt.Dimension(300, 50));
        tblDokumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokumenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDokumen);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        halamanUtama.addComp(new TambahDokumen());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblDokumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokumenMouseClicked
//        int baris = tblDokumen.rowAtPoint(evt.getPoint());
//        String nik = tblDokumen.getValueAt(baris, 1).toString();
//        
    }//GEN-LAST:event_tblDokumenMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int r = tblDokumen.getSelectedRow();
        if (r !=-1){ //maka sudah ada baris yg dipilih
            int kd = Integer.parseInt(tblDokumen.getValueAt(r, 1).toString());
            int pilih = JOptionPane.showConfirmDialog(this,"" //kolom ke 1 adalah kolom yang tadi di hidden
                    +"Apakah anda yakin?","Konfirmasi",
                    JOptionPane.YES_NO_OPTION); //dialog konfirmasi yes dan no
            if (pilih == 0) { 
                try {
                    java.sql.Connection c = Connection.MySQL(); //mendeteksi jika ada yang error
                    Statement st = c.createStatement();
                    String q = "DELETE FROM dokumen WHERE kode="+kd+"";
                    st.executeUpdate(q);
                    loadData("");
                    JOptionPane.showMessageDialog(this, "Data telah dihapus");
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // mencari teks yang ada pada Dokumen dengan memasukkan kata kunci
        String key = txtCari.getText();
        if (key.isEmpty()){
            loadData("");
        }else{
            loadData(key);
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int baris = tblDokumen.getSelectedRow();
        if (baris!=-1) {
            //String s = "12";
            //int x = Integer.parseInt(s);
            int kd =Integer.parseInt(tblDokumen.getValueAt(baris, 1).toString());
            String nama = tblDokumen.getValueAt(baris, 2).toString();
            String kategori =tblDokumen.getValueAt(baris, 3).toString();
            String lokasi=tblDokumen.getValueAt(baris, 4).toString();
            String deskripsi =tblDokumen.getValueAt(baris, 5).toString();
            String tanggal = tblDokumen.getValueAt(baris, 6).toString();
            Data d = new Data();
            d.setKode(kd);
            d.setNama(nama);
            d.setKategori(kategori);
            d.setLokasi(lokasi);
            d.setDeskripsi(deskripsi);
            d.setTanggal(tanggal);
            halamanUtama.addComp(new UbahDok(d));
        }
    }//GEN-LAST:event_btnUbahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDokumen;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    private void loadData(String key) {
        try {
            model.setRowCount(0);
            java.sql.Connection c = Connection.MySQL();
            Statement st = c.createStatement();
            String where = key.isEmpty()?"": " WHERE nama LIKE '%"+key+"%'";
            String q = "";
            ResultSet rs = st.executeQuery("SELECT * FROM dokumen"+where);
            int no = 0;
            while (rs.next()) {
                no++;
                int kd = rs.getInt("kode");
                String nama = rs.getString("nama");
                String kategori = rs.getString("kategori");
                String lokasi =rs.getString("lokasi");
                String deskripsi = rs.getString("deskripsi");
                String tanggal =rs.getString("tanggal");
                Object[] data = {no, kd, nama,kategori,lokasi,deskripsi,tanggal};
                model.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    private void pilihData(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
